### ISSUE TITLE
Failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [hyotang666/jingoh#2]
Building with SBCL 2.0.9.5-442f54894 / ASDF 3.3.1 for quicklisp dist creation.

Commit id 3adad51a39c7bdd747069e9df9ff087271fe9fd4

*jingoh.generator.test* fails to build with the following error:

```
Unhandled LOAD-SYSTEM-DEFINITION-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {100E570103}>: Error while trying to load definition for system jingoh.generator from pathname /home/quicklisp/quicklisp-controller/dist/build-cache/jingoh/ec40f03327aec6b92736a692e5ab320ea569b78f/jingoh-20201006-git/generator/jingoh.generator.asd: JINGOH.GENERATOR require ASDF/3.3.3 or later.

```

[Full log here](http://report.quicklisp.org/2020-10-06/failure-report/jingoh.html)

**Comment by hyotang666** [comment]
Thanks to report.
It is caused asdf version mismatch.
I will try to check 3.3.1 can build, please wait.

**Comment by hyotang666** [comment]
asdf:system-version is added after 3.3.2.11

https://github.com/fare/asdf/commit/3444455338abecdd2deaf851fd9a08e328ad4637

mmm.....

Ok.
Using asdf:component-version for old asdf.

**Comment by hyotang666** [comment]
Fixed. Thank you!
