### ISSUE TITLE
collect-spec-lines should open the file withe right external-format

### ISSUE THREAD

**Issue by Yehouda** [hyotang666/jingoh#3]
In reader/src/reader.lisp, the function **collect-spec-lines** opens the file associate with the stream that **|#?reader|** is called with, but it may end up with different external-format, and hence reading something else (or get an error).

In our tests I fixed it by calling   **collect-spec-lines**  like that `(collect-spec-lines pathname (stream-external-format stream))`, and in   **collect-spec-lines**  pass the external-format-format to **with-open-file**. I think an even better approach is to move whole of the **(unless \*lines\*..**  form into **collect-spec-lines** (and rename it to **ensure-spec-lines**).

**Comment by hyotang666** [comment]
Nice catch!
Thank you for your detailed report.

I will fix it soon.

**Comment by hyotang666** [comment]
Fixed.
